name: Update packages
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

jobs:
  cryptomator-check:
    runs-on: ubuntu-latest
    outputs:
      versionNumber: ${{ steps.latest-release.outputs.result }}
      hasNewerVersion: ${{ steps.has-newer-version.outputs.hasNewerVersion }}
    steps:
      - uses: actions/checkout@v2
      - name: Get current cryptomator version
        id: current-version
        run: |
          echo ::set-output name=version::$(./scripts/get_nuspec_verison.py ./packages/cryptomator/cryptomator.nuspec)
      - uses: actions/github-script@v6
        id: latest-release
        with:
          script: |
            const scripts = require('./scripts/cryptomator-release.js');
            return await scripts.latestRelease({github, context});
          result-encoding: string
      - name: Compare versions
        id: has-newer-version
        run: |
          echo ::set-output name=hasNewerVersion::$(./scripts/has_newer_version.py "${{steps.current-version.outputs.version}}" "${{steps.latest-release.outputs.result}}")
      - name: Get download url (failure means no .msi file)
        id: download-url
        if: ${{ steps.has-newer-version.outputs.hasNewerVersion == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            const scripts = require('./scripts/cryptomator-release.js');
            return await scripts.latestReleaseUrl({github, context});
          result-encoding: string

  cryptomator-update:
    runs-on: windows-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
