name: Update packages
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

jobs:
  cryptomator-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
